import { Link, useParams } from "react-router-dom";
import "./Supplier.css";

const pages: Record<string, { title: string; intro: string; points: string[] }> = {
  "sell-online": { title: "Sell online with Lumora", intro: "Reach shoppers across India with an easy, transparent marketplace built for growth.", points: ["Create your catalogue in minutes", "Reach customers nationwide", "Get paid securely and on time"] },
  "how-it-works": { title: "How selling works", intro: "A simple path from your first product listing to your first fulfilled order.", points: ["Register your business", "List products and set prices", "Pack orders and grow with insights"] },
  pricing: { title: "Pricing & commission", intro: "Keep more of what you earn with clear, upfront costs and no surprise fees.", points: ["Zero commission on eligible categories", "Transparent shipping fees", "No listing fee to get started"] },
  shipping: { title: "Shipping & returns", intro: "Reliable logistics and clear return policies designed to help you delight customers.", points: ["Pan-India delivery support", "Simple pickup scheduling", "Easy return tracking"] },
  growth: { title: "Grow your business", intro: "Use practical tools, trend insights and campaigns to build a brand customers remember.", points: ["Performance dashboard", "Seasonal campaign access", "Dedicated seller learning centre"] },
  "no-gst": { title: "Start selling without GST", intro: "Eligible sellers can start with their enrolment ID and grow at their own pace.", points: ["Check eligibility in minutes", "Guided onboarding", "Support when you need it"] },
};
const links = [["Sell Online", "sell-online"], ["How it works", "how-it-works"], ["Pricing & Commission", "pricing"], ["Shipping & Returns", "shipping"], ["Grow Business", "growth"], ["No GST?", "no-gst"]] as const;
function SupplierHeader() { return <header className="supplier-header"><Link className="supplier-brand" to="/supplier">Lumora <span>partner</span></Link><nav>{links.map(([label, slug]) => <Link key={slug} to={`/supplier/${slug}`}>{label}</Link>)}</nav><Link className="supplier-login" to="/login">Login</Link><Link className="supplier-cta" to="/supplier/sell-online">Start Selling</Link></header>; }
function Supplier() { return <div className="supplier-site"><SupplierHeader /><main><section className="supplier-hero"><div><p className="eyebrow">LUMORA PARTNER</p><h1>Build a business customers love.</h1><p>List products, reach millions and manage every sale from one calm, capable workspace.</p><div className="supplier-actions"><Link className="supplier-cta" to="/supplier/sell-online">Start selling free</Link><Link className="supplier-text-link" to="/supplier/how-it-works">See how it works →</Link></div><p className="supplier-note">No GSTIN? Eligible sellers can still get started.</p></div><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85" alt="Small business team collaborating" /></section><section className="supplier-stats"><div><b>0%</b><span>commission on eligible categories</span></div><div><b>19M+</b><span>customers to reach</span></div><div><b>24/7</b><span>seller support</span></div></section><section className="supplier-benefits"><p className="eyebrow">MADE FOR MOMENTUM</p><h2>Everything you need to sell with confidence</h2><div>{["Simple onboarding", "Reliable fulfilment", "Insights that help you grow"].map((title, index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{["Set up your digital shop with guided steps and practical tools.", "Keep orders moving with dependable pickup and delivery support.", "Understand demand and make better decisions, faster."][index]}</p></article>)}</div></section></main></div>; }
export function SupplierInfoPage() { const { page = "sell-online" } = useParams(); const content = pages[page] ?? pages["sell-online"]; return <div className="supplier-site"><SupplierHeader /><main className="supplier-info"><p className="eyebrow">LUMORA PARTNER</p><h1>{content.title}</h1><p>{content.intro}</p><div className="supplier-info-grid">{content.points.map((point, index) => <article key={point}><span>0{index + 1}</span><h2>{point}</h2><p>Designed to make your selling journey clearer, quicker and more rewarding.</p></article>)}</div><Link className="supplier-cta" to="/register">Create your seller account</Link></main></div>; }
export default Supplier;
